version: '3.4'

services:
  vueimagegallerybackend:
    image: vueimagegallerybackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8088:8088
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
